### ISSUE TITLE
chef-client error when --why-run mode enabled in require "chef-vault" section

### ISSUE THREAD

**Issue by lesha4ever** [chef/chef-vault#253] opened 2017-01-16 14:54 UTC
Chef Client version 12.17.44
I can't use chef-client --why-run for predicting changes. It always fails

```

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/my-cookbook/recipes/install.rb
================================================================================

LoadError
---------
cannot load such file -- chef-vault

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/my-cookbook/recipes/install.rb:16:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/my-cookbook/recipes/install.rb:

 14:  
 15:  chef_gem "chef-vault"
 16>> require "chef-vault"
 17:  


Platform:
---------
x86_64-linux

```

Any solution to use chef-vault with --why-run mode?

**Comment by thommay** [comment] 2017-01-16 15:39
Hi,
you'll either need to have the chef-vault gem installed, or rescue the require so that chef can keep going. In that case, though, you won't be able to get vault items and so your run won't work the way you expect it to. 
Why Run Mode is not a suitable tool for testing chef runs for correctness, and we strongly recommend using test-kitchen along with an automated test suite such as inspec to ensure that your recipes function as intended.
I'm closing this issue since questions like this are better asked on [Discourse](https://discourse.chef.io) or on [Slack](http://community-slack.chef.io/).

**Closed by thommay** 2017-01-16 15:39 UTC
