### ISSUE TITLE
ERROR: cannot load such file -- chef-vault

### ISSUE THREAD

**Issue by 141984** [chef/chef-vault#268] opened 2017-04-12 15:23 UTC
Hi All,

Since last night all chef-clients are failing while trying to load gem chef-vault. My cookbooks have 
`chef_gem "chef-vault"` and `require "chef-vault"` and this gem is present in my base machine gem and chef gem, for when i run gem list and chef gem list i can see the gem installed.

I have tired specifying a version number as well, still it fails.

What could be the cause of this failure?

   

> ================================================================================[0m
>                                  [31mRecipe Compile Error in /var/chef/cache/cookbooks/myCookbook/recipes/deploy_pkg.rb[0m
>                                  ================================================================================[0m
>                                  
>                                  [0mLoadError[0m
>                                  ---------[0m
>                                  cannot load such file -- chef-vault[0m
>                                  
>                                  [0mCookbook Trace:[0m
>                                  ---------------[0m
>                                    /var/chef/cache/cookbooks/httpd/recipes/setup_crts.rb:6:in `from_file'
>                                  [0m  /var/chef/cache/cookbooks/myCookbook/recipes/deploy_pkg.rb:12:in `from_file'[0m
>                                  
>                                  [0mRelevant File Content:[0m
>                                  ----------------------[0m
>                                  /var/chef/cache/cookbooks/httpd/recipes/setup_crts.rb:
>                                  [0m
>                                  [0m  1:  include_recipe "#{cookbook_name}::install_httpd"
>                                  [0m  2:  
>                                  [0m  3:  chef_gem "chef-vault" do
>                                  [0m  4:    version "2.9.1"
>                                  [0m  5:  end
>                                  [0m  6>> require "chef-vault"
>                                  [0m  7:  
>                                  [0m  8:  crt = "#{node[:environment]}" + "-httpd-ssl-crt"
>                                  [0m  9:  key = "#{node[:environment]}" + "-httpd-ssl-key"
>                                  [0m 10:  
>                                  [0m 11:  ssl_crt = ChefVault::Item.load("myOrg", crt)
>                                  [0m 12:  ssl_key = ChefVault::Item.load("myOrg", key)
>                                  [0m 13:  
>                                  [0m 14:  # setup ssl certs
>                                  [0m 15:  file "#{node['httpd']['ssl_certificate_crt_path']}" do
>                                  [0m
>                                  [0mSystem Info:[0m
>                                  ------------[0m
>                                  chef_version=13.0.118
>                                  [0mplatform=amazon
>                                  [0mplatform_version=2016.09
>                                  [0mruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
>                                  [0mprogram_name=chef-client worker: ppid=366;start=15:04:10;
>                                  [0mexecutable=/opt/chef/bin/chef-client[0m
>                                  
>                                  [0m[0m
>                                  Running handlers:[0m
>                                  [2017-04-12T15:04:11+00:00] ERROR: Running exception handlers
>                                  Running handlers complete
>                                  [0m[2017-04-12T15:04:11+00:00] ERROR: Exception handlers complete
>                                  Chef Client failed. 0 resources updated in 01 seconds[0m
>                                  [2017-04-12T15:04:11+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
>                                  [2017-04-12T15:04:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
>                                  [2017-04-12T15:04:11+00:00] ERROR: cannot load such file -- chef-vault
>                                  [2017-04-12T15:04:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by thommay** [comment] 2017-04-12 15:33
Please provide the full stack trace from `/var/chef/cache/chef-stacktrace.out`, but we've not tested Chef Vault 2.9.1 with Chef Client 13, and in fact released Chef Vault 3 recently which definitely works.

**Comment by 141984** [comment] 2017-04-12 18:31
[chef-stacktrace.txt](https://github.com/chef/chef-vault/files/917386/chef-stacktrace.txt)

**Comment by 141984** [comment] 2017-04-12 18:40
i updated my chef-client to Chef: 13.0.118 and now I'm getting the same kind of error of chef/provisioning 


Generated at 2017-04-12 23:58:16 +0530
LoadError: cannot load such file -- chef/provisioning
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/dsl/chef_provisioning.rb:53:in `load_chef_provisioning'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/dsl/chef_provisioning.rb:42:in `with_driver'
/var/chef/cache/cookbooks/twilioServices/recipes/docker_provision.rb:1:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook_version.rb:205:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:163:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:160:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:160:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:77:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:187:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'

**Comment by 141984** [comment] 2017-04-13 12:48
LoadError: cannot load such file -- chef-vault
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/chef/cache/cookbooks/nginx/recipes/setup_crts.rb:4:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook_version.rb:205:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:293:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:293:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/twilioServices/recipes/deploy_pkg.rb:12:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook_version.rb:205:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:338:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:163:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:160:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:160:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context/cookbook_compiler.rb:77:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/run_context.rb:187:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'

**Comment by stevengnelson** [comment] 2017-04-13 14:39
We're using Berks to manage external cookbooks, and encountered the same issue. Adding `recipe[chef-vault::default]` to our role installed the gem to let chef-client run successfully.

Our source for chef-vault is https://supermarket.chef.io/cookbooks/chef-vault/versions/2.1.1, which doesn't provide Chef Vault 3.

**Comment by 141984** [comment] 2017-04-13 14:41
Hey,

I have figured out the issue. I am using chef-provisioning-docker to create containers, and inside the container it was downloading chef v13.0.118. With chef v13.0.118 'chef_gem "chef-vault"' in the cookbooks was not downloading the gem. I have worked around this by baking chef and chef-vault gem inside the base container image that I use, but its still an issue with chef v13.0.118 where it is not downloading the gem specified in 'chef_gem'. 

Has this way of installing gems changed in v13.0.118?

**Comment by lamont-granquist** [comment] 2017-04-17 16:59
should be fixed by moving the chef dep in chef-vault to a dev depenedency?

https://github.com/chef/chef-vault/commit/3e7452555e298cc179e1ee485ca508e6c64a9f16

**Comment by lamont-granquist** [comment] 2017-04-17 17:15
and this sort of is not a bug in the gem metadata feature.

we know that we can't install native gems using gem metadata by design.

while chef itself isn't a native gem, it has deps on native gems, so it cannot be installed this way (also:  chefception)

so that means that no gem that depends on chef can be installed using the gem metadata feature.

**Comment by lamont-granquist** [comment] 2017-04-17 17:38
I'm getting this now:

```
Installing Cookbook Gems:
[2017-04-17T10:36:39-07:00] INFO: Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing chef-vault 3.0.1
Using bundler 1.14.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

there are no dev gems being installed, so closing this as fixed.

**Closed by lamont-granquist** 2017-04-17 17:38 UTC
