### ISSUE TITLE
knife search returns nodes but knife vault does not encrypt the data using those nodes public keys

### ISSUE THREAD

**Issue by jhammerman79** [chef/chef-vault#190] opened 2016-01-11 22:47 UTC
Hi Chef Vault developers,

I have a staging instance of Chef Server and a production instance of Chef Server. On Staging, 

```
#knife vault update secrets aws_secret_key -S "role:inf"
```

Causes the clients to be detected and added appropriately.

On Prod, even though this search query returns results, no clients are ever added.

This is Chef 12.5.1, with the latest version of the Vault available in the Supermarket, running on Ubuntu Precise.

I have tried deleting and recreating the databag, and restarting the Chef Server subprocesses.

When I execute the query, the chef-solr log shows:

```
INFO: [] webapp=/solr path=/select params={sort=X_CHEF_id_CHEF_X+asc&indent=off&start=0&q=content:role__%3D__inf&wt=json&fq=%2BX_CHEF_database_CHEF_X:chef_00000000000000000000000000000000+%2BX_CHEF_type_CHEF_X:node&rows=1000} hits=4 status=0 QTime=80
```

So I know that Vault found four clients when querying Solr.

```
#knife data bag show secrets aws_secret_key_keys
```

Reveals

```
aws_secret_key_keys
Unencrypted data bag detected, ignoring any provided secret options.
:            <public key>
admins:       jhammerman
clients:
id:           aws_secret_key_keys
jhammerman:   <public key>

search_query: role:inf
```

I have included this to show the public key that prepends the other elements int he databag with an an empty key field.

Thanks in advance for any assistance you can provide.
Joseph Hammerman

**Comment by thommay** [comment] 2016-01-21 14:24
hi @jhammerman79, please can you run `knife vault update secrets aws_secret_key -S "role:inf" -VVV` in your production environment and mail me the output? thom@chef.io .

**Comment by l8nite** [comment] 2016-02-12 21:51
Any luck on this @jhammerman79? I'm seeing something similar here.

**Comment by jhammerman79** [comment] 2016-02-12 23:50
Hey sorry all, missed this. I will run the command when I get back in on Tuesday and let you know the output.Joe 

    On Friday, February 12, 2016 4:51 PM, Shaun Guth <notifications@github.com> wrote:
 

 Any luck on this @jhammerman79? I'm seeing something similar here.—

**Comment by thommay** [comment] 2016-02-23 16:51
@jhammerman79 hi, sorry to nag but it'd be great to get your problem isolated. please run `knife vault update secrets aws_secret_key -S "role:inf" -VVV` and send the output to thom@chef.io

**Comment by thommay** [comment] 2016-03-21 18:33
@l8nite are you still seeing this problem? If you can do the following:
```
knife vault update secrets aws_secret_key -S "role:inf" -VV
```
and mail the output to thom@chef.io please that would be great.

**Comment by l8nite** [comment] 2016-03-23 19:01
@thommay No this appears to have been resolved (I just did a clean install of chef-vault 2.8.0)

**Comment by thommay** [comment] 2016-03-29 16:49
OK. I'm going to close this issue since we don't seem able to reproduce right now.

**Closed by thommay** 2016-03-29 16:49 UTC
