### ISSUE TITLE
knife vault refresh undefined local variable or method 'vault'

### ISSUE THREAD

**Issue by tysonjhayes** [chef/chef-vault#316] opened 2018-06-05 22:44 UTC
running knife vault refresh results in a NameError.  Please let me know what data you need as I'm pretty unfamiliar with Chef/chef-vault.

OS: Windows 10 RS4/Windows 2012 R2
Chef:
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

PS C:\chef> chef gem list chef-vault

*** LOCAL GEMS ***

chef-vault (3.3.0)

```
knife vault refresh credentials account --clean-unknown-clients -VV
INFO: Using configuration from C:/chef/knife.rb
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-vault-3.3.0/lib/chef-vault/item.rb:363:in `refresh': undefined
local variable or method `vault' for #<ChefVault::Item:0x00000000062eae18> (NameError)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-vault-3.3.0/lib/chef/knife/vault_refresh.rb:45:in
`run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/knife.rb:442:in
 `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/local_mode.rb:4
4:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/knife.rb:441:in
 `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/knife.rb:219:in
 `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/kni
fe.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/bin/knife:25:in `<top (r
equired)>'
        from C:/opscode/chefdk/bin/knife:279:in `load'
        from C:/opscode/chefdk/bin/knife:279:in `<main>'
```

**Comment by thommay** [comment] 2018-06-06 10:57
Ah, thanks. ChefVault is trying to show you an error message:
> `credentials/account` does not have a stored search_query probably because it was created with an older version of chef-vault. Use 'knife vault update' to update the databag with the search query.

but failing to display the data bag name. I'll get that fixed.

**Comment by tysonjhayes** [comment] 2018-06-06 20:00
I ran knife vault update on the data bag and am still seeing the error, am I being expected to update with a search term or something?

**Comment by sanga1794** [comment] 2020-06-05 08:26
Hi @tysonjhayes, I have followed the steps below with the latest chef-vault,
1) i have created a vault without adding search query
	knife vault create passwords user_details -J root.json

	/home/ad.msystechnologies.com/s.ausekar/.rvm/gems/ruby-2.7.0/gems/chef-vault-4.0.1/lib/chef-vault/item_keys.rb:237: warning: constant Net::HTTPServerException is deprecated

2) I tried to refresh the vault, got below result
	knife vault refresh passwords user_details

	ERROR: ChefVault::Exceptions::SearchNotFound: passwords/user_details does not have a stored search_query, probably because it was created with an older version of chef-vault. Use 'knife vault update' to update the databag with the search query.
3) I have updated the vault with the search query
	knife vault update passwords user_details -S "role:webserver"
4) I have again tried to refresh vault, its working now
	knife vault refresh passwords user_details

@tysonjhayes, I hope same work around is also worked for you. Please update the status if the issue is got resolved or still some issues you are facing. Thanks.

**Comment by sanga1794** [comment] 2020-06-08 13:05
Hi @tysonjhayes, for time being we are closing this issue. Add comment if any queries.

**Closed by sanga1794** 2020-06-08 13:05 UTC
