### ISSUE TITLE
Bootstrap Vault Item/JSON/File failing on multiple node bootstrapping

### ISSUE THREAD

**Issue by johnnystarr** [chef/chef-vault#229] opened 2016-10-06 21:38 UTC
I am attempting to bootstrap multiple nodes at the same time while passing `--bootstrap-vault-json`.  I am running this as a user who is an admin on all 3 vaults.  If I run them serially (one at a time) there are no issues.  However, when I concurrently kick off multiple runs every time a different vault item will fail:

```
knife bootstrap 10.0.0.1 -N web01 -E dev -x admin -P $password --sudo --no-host-key-verify -r 'recipe[apache2]' --bootstrap-vault-json '{"passwords":"apache","keys":"ssl","users":"linux"}'
knife bootstrap 10.0.0.2 -N web02 -E dev -x admin -P $password --sudo --no-host-key-verify -r 'recipe[apache2]' --bootstrap-vault-json '{"passwords":"apache","keys":"ssl","users":"linux"}'
knife bootstrap 10.0.0.3 -N web03 -E dev -x admin -P $password --sudo --no-host-key-verify -r 'recipe[apache2]' --bootstrap-vault-json '{"passwords":"apache","keys":"ssl","users":"linux"}'
```
We get an error like the following:

```
ChefVault::Exceptions::SecretDecryption
---------------------------------------
passwords/apache is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!
```

Note, I am kicking off these system calls within a Ruby script using `spawn`.  This allows me concurrent output to TeamCity.  I have tried kicking off each command in the background with the `&` character appended to each line, however this does not work because these child procs die when the job is done.

Ideally, I would like some comments on this exception and determine if this is a bug in vault.  Although I would happily accept alternative methods for bootstrapping multiple nodes with vault items / json / files.  Is it possible that we're dealing with a lock file for vault or knife?  Perhaps because the resource is shared across multiple local sessions we're running into a racing condition?

Please advise.  Thanks!
-Johnny Starr

**Comment by thommay** [comment] 2016-10-07 09:44
You're seeing a race; each of those processes is attempting to write to the key, probably simultaneously, with the data it got - which won't contain the data from the other two nodes. This is not a bug in vault; just the way it - and data bags - were designed. The quick work around is probably to put enough of a sleep in to get each node past the point of writing the vault out before the next one starts.

**Comment by thommay** [comment] 2016-10-19 10:53
Closing this since there's nothing that we can do in vault - we'd need vector clocks or something in the chef server to handle this case.

**Closed by thommay** 2016-10-19 10:53 UTC

**Comment by davidsainty** [comment] 2017-08-04 00:52
It does kind of seem like a bug.

Can't the server side be extended to solve this bug?

An atomic "change to value X if the current value matches Y" could be used to fix this, without needing any difficult-to-implement changes.

We use a lock databag to solve this problem, which is currently supported by the Chef server (create-or-fail appears to be reliably atomic).  But it would be nice to not have to fix it ourselves and be able to rely on vault to not lose changes.
